src/Entity/CV.php
<?php

namespace App\Entity;

use App\Repository\CVRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CVRepository::class)
 */
class CV
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $competences;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $experiences;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $formations;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $hobbies;

    /**
     * @ORM\Column(type="string", length=15, nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $social;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $subtitle;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getCompetences(): ?array
    {
        return isset($this->competences) ? unserialize($this->competences) : null;
    }

    public function setCompetences(?array $competences): self
    {
        $this->competences = serialize($competences);

        return $this;
    }

    public function getExperiences(): ?array
    {
        return isset($this->experiences) ? unserialize($this->experiences) : null;
    }

    public function setExperiences(?array $experiences): self
    {
        $this->experiences = serialize($experiences);

        return $this;
    }

    public function getFormations(): ?array
    {
        return isset($this->formations) ? unserialize($this->formations) : null;
    }

    public function setFormations(?array $formations): self
    {
        $this->formations = serialize($formations);

        return $this;
    }

    public function getHobbies(): ?array
    {
        return isset($this->hobbies) ? unserialize($this->hobbies) : null;
    }

    public function setHobbies(?array $hobbies): self
    {
        $this->hobbies = serialize($hobbies);

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getSocial(): ?string
    {
        return unserialize($this->social);
    }

    public function setSocial(?string $social): self
    {
        $this->social = serialize($social);

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSubtitle(): ?string
    {
        return $this->subtitle;
    }

    public function setSubtitle(?string $subtitle): self
    {
        $this->subtitle = $subtitle;

        return $this;
    }

    public function addCompetence(array $competence){
        $competences = unserialize($this->competences) ? unserialize($this->competences) : [];
        array_push($competences, $competence);
        $this->competences = serialize($competences);
        return $this;
    }

    public function addExperience(array $experience){
        $experiences = unserialize($this->experiences) ? unserialize($this->experiences) : [];
        array_push($experiences, $experience);
        $this->experiences = serialize($experiences);
        return $this;
    }

    public function addFormation(array $formation){
        $formations = unserialize($this->formations) ? unserialize($this->formations) : [];
        array_push($formations, $formation);
        $this->formations = serialize($formations);
        return $this;
    }

    public function addHobby(array $hobby){
        $hobbies = unserialize($this->hobbies) ? unserialize($this->hobbies) : [];
        array_push($hobbies, $hobby);
        $this->hobbies = serialize($hobbies);
        return $this;
    }
}

src/Controller/CVController.php
<?php

namespace App\Controller;

use App\Entity\CV;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;

class CVController extends AbstractController
{
    /**
     * @Route("/cv", name="cv")
     */
    public function index()
    {
        //$entityManager = $this->getDoctrine()->getManager();
        // $cv = $this->getDoctrine()
        //     ->getRepository(CV::class)
        //     ->findAll()[0];
        
        $cv = new CV();
        $cv->setFirstName("Kévin");
        $cv->setLastName("Mercier");
        $cv->setTitle("Développeur PHP");
        $cv->setSubtitle("En contrat de professionnalisation");
        $cv->setAddress("1, rue Jean-Marie Ecorchard\nAppartement B12\n35 131 Chartres-de-Bretagne");
        $cv->setPhone("0768590601");

        $cv->addCompetence([
                "name" => "Travail en équipe, précision, gestion des priorités",
                "desc" => ""
            ])
        ->addCompetence([
            "name" => "Languages informatiques",
            "desc" => "PHP, MySQL, Python, HTML/JS/CSS/SCSS, C/C++"
        ])
        ->addCompetence([
            "name" => "Frameworks, librairies, bibliothèques et autres outils de développement",
            "desc" => "Symfony(PHP), Numpy/Pandas/Matplotlib(Python), JQuery(JS), WebPack"
        ])
        ->addCompetence([
            "name" => "Pack office, SolidWorks(CAO)",
            "desc" => ""
        ]);

        $cv->addExperience([
            "name" => "Juillet 2018 - Aujourd'hui : Analyste MET chez ITGA à Rennes (35)",
            "desc" => "Analyse de prélèvements d'air et de matériaux afin de déterminer la présence d'amiante"

        ])
        ->addExperience([
            "name" => "Mai 2017 - Juillet 2018 : Technicien de laboratoire chez ITGA à Rennes (35)",
            "desc" => "Préparation d'échantillons de matériaux potentiellement amiantés en vue d'une analyse au MET"

        ])
        ->addExperience([
            "name" => "Juin 2015 - Octobre 2015 : Aide de laboratoire au CHU de Pontchaillou à Rennes (35)",
            "desc" => "Réception des prélèvements, gestion des prélèvements urgents, centrifugation, décantation"
        ])
        ->addExperience([
            "name" => "Avril 2015 - Juin 2015 : Inventoriste chez RGIS à Rennes (35)",
            "desc" => "Réalisations d'inventaires rapides et précis"
        ])
        ->addExperience([
            "name" => "Juillet 2014 - Août 2014 : Aide de laboratoire au CHU de Pontchaillou à Rennes (35)",
            "desc" => "Préparation des commandes, réception des prélèvements, laverie, stérilisation du matériel"
        ])
        ->addExperience([
            "name" => "Avril 2014 - Juin 2014 : Stagiaire technicien d'analyse bactériologiques chez Novescia à Wissous (91)",
            "desc" => "Vérification sur site des méthodes d'un automate d'hémoculture. Ensemencement, lecture et interprétation des résultats."
        ]);

        $cv->addFormation([
            "name" => "2014 - 2015 : Université de Rennes 1 à Rennes (35)",
            "desc" => "L1 Informatique"
        ])
        ->addFormation([
            "name" => "2012 - 2014 : Université de Bretagne Sud à Pontivy (56)",
            "desc" => "I.U.T Génie chimique - génie des procédés (diplôme non obtenu)"
        ])
        ->addFormation([
            "name" => "2012 : Lycée privé de l'Assomption à Rennes (35)",
            "desc" => "Baccalauréat scientifique (mention assez bien)"
        ]);

        $cv->addHobby([
            "name" => "Science, découverte (électronique, informatique, astronomie)",
            "desc" => ""
        ])
        ->addHobby([
            "name" => "Voyages",
            "desc" => ""
        ]);
        //$entityManager->flush();
        return $this->render("cv/cv.html.twig", ["cv" => $cv]);
    }
}

templates/cv/cv.html.twig
{% extends 'base.html.twig' %}

{% block title %}
{{ cv.title }}
{% endblock %}

{% block stylesheets %}
{{ encore_entry_link_tags('cv') }}
{% endblock %}

{% block body %}
<div class="container-lg cv-container container-fluid">
    <div class="row">
        <aside id="presentation" class="col-lg-3">
            <div class="address item">
                <h2>{{ cv.firstName }} {{ cv.lastName }}</h2>
                <address>
                    {{ cv.address|nl2br }}
                </address>
            </div>
            <div class="tel item">
                {{ include("icons/tel.html.twig") }}
                {{ cv.phone }}
            </div>
            <div class="email item text-center">
                <a class="email btn btn-outline-primary" id="btn-email" href="{{ path('contact') }}" target="_blank">
                    {{ include("icons/email.html.twig") }}
                    M'envoyer un email
                </a>
            </div>
            <div class="social item d-flex justify-content-center">
                <div class="p-2">
                    <a href="https://github.com/mercierkevin35" target="_blank">
                        {{ include("icons/github.html.twig") }}
                    </a>
                </div>
                <div class="p-2">
                    <a href="https://www.linkedin.com/in/kevin-mercier-197660100/" target="_blank">
                        {{ include("icons/linkedin.html.twig") }}
                    </a>
                </div>
            </div>

        </aside>
        <div id="content" class="col-lg-9">
            <div class="title-container text-center">
                <h1 class="main-title">{{ cv.title }}</h1>
                {% if cv.subtitle is defined and cv.subtitle is not empty %}
                    <h2 class="subtitle">{{ cv.subtitle }}</h2>
                {% endif %}
            </div>

            
            {% if cv.competences is defined and cv.competences is not empty %}
            <section id="competences" class="category">
                <h2 class="cat-title">Compétences</h2>
                <hr>
                <dl>
                {% for competence in cv.competences %}
                    <dt>{{competence.name}}</dt>
                    <dd>{{competence.desc}}</dd>
                {% endfor %}
                </dl>
            </section>
            {% endif %}
            {% if cv.experiences is defined and cv.experiences is not empty %}
            <section id="experiences" class="category">
                <h2 class="cat-title">Expériences</h2>
                <hr>
                <dl>
                {% for experience in cv.experiences %}
                    <dt>{{experience.name}}</dt>
                    <dd>{{experience.desc}}</dd>
                {% endfor %}
                </dl>
            </section>
            {% endif %}
            {% if cv.formations is defined and cv.formations is not empty %}
            <section id="formations" class="category">
                <h2 class="cat-title">Formations</h2>
                <hr>
                <dl>
                {% for formation in cv.formations %}
                    <dt>{{formation.name}}</dt>
                    <dd>{{formation.desc}}</dd>
                {% endfor %}
                </dl>
            </section>
            {% endif %}
            {% if cv.hobbies is defined and cv.hobbies is not empty %}
            <section id="hobbies" class="category">
                <h2 class="cat-title">Centres d'intérêt</h2>
                <hr>
                <dl>
                {% for hobby in cv.hobbies %}
                    <dt>{{hobby.name}}</dt>
                    <dd>{{hobby.desc}}</dd>
                {% endfor %}
                </dl>
            </section>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

{% block javascripts %}
{{ encore_entry_script_tags('cv') }}
{% endblock %}